#Example 1 showing basic usage.
!ArenaConfig
arenas:
  0: !Arena
    t: 0 #no time limit if zero, otherwise need to get to goal before time limit elapses
    items:
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 10, y: 0, z: 20}
      rotations: [0]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 38}

    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 20}
      
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 30, y: 0, z: 10}
      rotations: [0]
      sizes: 
      - !Vector3 {x: 2, y: 3, z: 10}
      
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 5, y: 0, z: 37.5}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 1, y: 0, z: 1}
      rotations: [0]


